# Copyright (c) 2010 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
{
  'variables': {
    'chromium_code': 1,
  },
  'targets': [
    {
      'target_name': 'jni_headers',
      'type': 'none',
      'actions': [
        {
          'action_name': 'generate_jni_headers',
          'inputs': [
              '../../base/android/jni_generator/jni_generator.py',
              '../java/apps/chrome/src/com/google/android/apps/chrome/BrowserVersion.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/ChromeBrowserProvider.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/preferences/ChromeNativePreferences.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/ChromeViewListAdapter.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/GpuProfiler.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/infobar/InfoBarContainer.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/InstantTab.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/MemoryUsageMonitor.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/NetworkConnectivityReceiver.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/LocationBar.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/partnerbookmarks/PartnerBookmarksShim.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/Tab.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/glui/GLUIFunctorRenderer.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/UmaRecordAction.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/bridge/AutocompleteController.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/database/SQLiteCursor.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/preferences/WebsiteSettingsUtils.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/sync/SyncSetupFlowAdapter.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/sync/SyncSetupManager.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/sync/GoogleAutoLogin.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/thumbnail/ETC1.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/uma/UmaSessionStats.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/utilities/ProcessUtils.java',
              '../java/apps/chrome/src/com/google/android/apps/chrome/utilities/URLUtilities.java',
              '../../content/android/java/org/chromium/content/browser/BrowserProcessMain.java',
              '../../content/android/java/org/chromium/content/browser/ChromeHttpAuthHandler.java',
              '../../content/android/java/org/chromium/content/browser/ChromeVideoView.java',
              '../../content/android/java/org/chromium/content/browser/ChromeView.java',
              '../../content/android/java/org/chromium/content/browser/ChromeViewClient.java',
              '../../content/android/java/org/chromium/content/browser/CommandLine.java',
              '../../content/android/java/org/chromium/content/browser/DownloadController.java',
              '../../content/android/java/org/chromium/content/browser/LocationProvider.java',
              '../../content/android/java/org/chromium/content/browser/RemoteDebuggingController.java',
              '../../content/android/java/org/chromium/content/browser/TouchPoint.java',
              '../../content/android/java/org/chromium/content/browser/WaitableNativeEvent.java',
              '../../content/android/java/org/chromium/content/browser/AndroidProtocolAdapter.java',
              '../../content/android/java/org/chromium/content/browser/TraceEvent.java',
              '../../content/android/java/org/chromium/content/browser/UserAgent.java',
              '../../content/android/java/org/chromium/content/browser/WebSettings.java',
              '../../content/android/java/org/chromium/content/browser/content/MemoryThreshold.java',
              '../../content/android/java/org/chromium/content/browser/net/AndroidNetworkLibrary.java',
              '../../content/android/java/org/chromium/content/browser/net/ProxyChangeListener.java',
          ],
          'outputs': [
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/browser_version_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_browser_provider_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_native_preferences_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_view_list_adapter_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/gpu_profiler_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/info_bar_container_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/instant_tab_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/memory_usage_monitor_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/network_connectivity_receiver_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/location_bar_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/partner_bookmarks_shim_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/tab_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/glui_functor_renderer_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/uma_record_action_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/autocomplete_controller_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/sqlite_cursor_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/website_settings_utils_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/sync_setup_flow_adapter_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/sync_setup_manager_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/google_auto_login_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/etc1_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/uma_session_stats_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/process_utils_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/url_utilities_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/browser_process_main_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_http_auth_handler_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_video_view_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_view_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/chrome_view_client_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/command_line_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/download_controller_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/location_provider_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/remote_debugging_controller_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/touch_point_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/waitable_native_event_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/android_protocol_adapter_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/trace_event_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/user_agent_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/web_settings_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/content/jni/memory_threshold_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/net/jni/android_network_library_jni.h',
              '<(SHARED_INTERMEDIATE_DIR)/net/jni/proxy_change_listener_jni.h',
          ],
          'action': [
            'python',
            '../../base/android/jni_generator/jni_generator.py',
            '-o',
            '<@(_inputs)',
            '<@(_outputs)',
          ],
        },
        {
          'action_name': 'generate_jni_headers_for_system_classes',
          'inputs': [
              '../../base/android/jni_generator/jni_generator.py',
              '<(android_src)/out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes/java/io/InputStream.class',
          ],
          'outputs': [
              '<(SHARED_INTERMEDIATE_DIR)/android/jni/input_stream_jni.h',
          ],
          'action': [
            'python',
            '../../base/android/jni_generator/jni_generator.py',
            '-p',
            '-o',
            '<@(_inputs)',
            '<@(_outputs)',
          ],
        },
      ],
    },
  ],
}

# Local Variables:
# tab-width:2
# indent-tabs-mode:nil
# End:
# vim: set expandtab tabstop=2 shiftwidth=2:
